baseURL = "https://goodeyesss.day/"
title = "Good Eyes S.S"

# 多言語設定
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[languages]
  [languages.ja]
    languageName = "日本語"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.hr]
    languageName = "Hrvatski"
    weight = 3
  [languages.it]
    languageName = "Italiano"
    weight = 4

[pagination]
  pagerSize = 3

# [params]
#   description = "世界中のニュースを"
